"""
Backtesting engine module.

Provides event-driven and vectorized backtesting, market simulation
with realistic slippage and transaction costs, and performance analytics.
"""

from quant_trading_system.backtest.analyzer import (
    BenchmarkMetrics,
    DrawdownMetrics,
    PerformanceAnalyzer,
    PerformanceReport,
    ReturnMetrics,
    RiskAdjustedMetrics,
    StatisticalTests,
    TradeMetrics,
    VisualizationData,
)
from quant_trading_system.backtest.engine import (
    BacktestConfig,
    BacktestEngine,
    BacktestMode,
    BacktestState,
    DataHandler,
    ExecutionMode,
    PandasDataHandler,
    Strategy,
    Trade,
    VectorizedBacktest,
)
from quant_trading_system.backtest.optimizer import (
    BaseOptimizer,
    BayesianOptimizer,
    GeneticOptimizer,
    GridSearchOptimizer,
    OptimizationResult,
    OptimizationWindow,
    OverfitDetector,
    ParameterSpace,
    RandomSearchOptimizer,
    StrategyOptimizer,
    WalkForwardOptimizer,
)
from quant_trading_system.backtest.simulator import (
    BaseSlippageModel,
    BidAskSimulator,
    FillResult,
    FillSimulator,
    FillType,
    FixedSlippageModel,
    LatencySimulator,
    MarketConditions,
    MarketImpactModel,
    MarketSimulator,
    SlippageModel,
    SlippageModelFactory,
    VolatilitySlippageModel,
    VolumeBasedSlippageModel,
    create_optimistic_simulator,
    create_pessimistic_simulator,
    create_realistic_simulator,
)

__all__ = [
    # Engine
    "BacktestConfig",
    "BacktestEngine",
    "BacktestMode",
    "BacktestState",
    "DataHandler",
    "ExecutionMode",
    "PandasDataHandler",
    "Strategy",
    "Trade",
    "VectorizedBacktest",
    # Simulator
    "BaseSlippageModel",
    "BidAskSimulator",
    "FillResult",
    "FillSimulator",
    "FillType",
    "FixedSlippageModel",
    "LatencySimulator",
    "MarketConditions",
    "MarketImpactModel",
    "MarketSimulator",
    "SlippageModel",
    "SlippageModelFactory",
    "VolatilitySlippageModel",
    "VolumeBasedSlippageModel",
    "create_optimistic_simulator",
    "create_pessimistic_simulator",
    "create_realistic_simulator",
    # Analyzer
    "BenchmarkMetrics",
    "DrawdownMetrics",
    "PerformanceAnalyzer",
    "PerformanceReport",
    "ReturnMetrics",
    "RiskAdjustedMetrics",
    "StatisticalTests",
    "TradeMetrics",
    "VisualizationData",
    # Optimizer
    "BaseOptimizer",
    "BayesianOptimizer",
    "GeneticOptimizer",
    "GridSearchOptimizer",
    "OptimizationResult",
    "OptimizationWindow",
    "OverfitDetector",
    "ParameterSpace",
    "RandomSearchOptimizer",
    "StrategyOptimizer",
    "WalkForwardOptimizer",
]
