"""
Alpha generation module.

Contains alpha factor base classes, momentum alphas, mean reversion alphas,
ML-generated alphas, and alpha combination strategies.
"""

from .alpha_base import (
    AlphaFactor,
    AlphaHorizon,
    AlphaMetrics,
    AlphaSignal,
    AlphaType,
    CompositeAlpha,
    AlphaRegistry,
)
from .alpha_combiner import (
    AlphaCombiner,
    AlphaNeutralizer,
    AlphaOrthogonalizer,
    AlphaWeight,
    AlphaWeighter,
    CombinerConfig,
    CompositeAlphaFactor,
    DecayWeighter,
    EqualWeighter,
    ICWeighter,
    InverseVolatilityWeighter,
    NeutralizationMethod,
    OptimizedWeighter,
    OrthogonalizationMethod,
    RankWeighter,
    SharpeWeighter,
    WeightingMethod,
    create_combiner,
)
from .mean_reversion_alphas import (
    BollingerReversion,
    HalfLifeReversion,
    KeltnerReversion,
    OUReversion,
    RsiReversion,
    SpreadReversion,
    StochasticReversion,
    VolumeWeightedReversion,
    ZScoreReversion,
    create_mean_reversion_alphas,
)
from .ml_alphas import (
    EnsembleMLAlpha,
    FeatureImportanceAlpha,
    LightGBMAlpha,
    LinearAlpha,
    MLAlpha,
    NeuralNetAlpha,
    RandomForestAlpha,
    XGBoostAlpha,
    create_ml_alphas,
)
from .momentum_alphas import (
    BreakoutMomentum,
    CrossoverMomentum,
    MacdMomentum,
    MomentumAcceleration,
    MomentumQuality,
    PriceMomentum,
    RelativeMomentum,
    RsiMomentum,
    TrendStrength,
    VolumeWeightedMomentum,
    create_momentum_alphas,
)

__all__ = [
    # Base classes
    "AlphaFactor",
    "AlphaType",
    "AlphaHorizon",
    "AlphaSignal",
    "AlphaMetrics",
    "CompositeAlpha",
    "AlphaRegistry",
    # Momentum alphas
    "PriceMomentum",
    "RsiMomentum",
    "MacdMomentum",
    "TrendStrength",
    "BreakoutMomentum",
    "MomentumAcceleration",
    "RelativeMomentum",
    "CrossoverMomentum",
    "VolumeWeightedMomentum",
    "MomentumQuality",
    "create_momentum_alphas",
    # Mean reversion alphas
    "BollingerReversion",
    "ZScoreReversion",
    "HalfLifeReversion",
    "RsiReversion",
    "KeltnerReversion",
    "OUReversion",
    "SpreadReversion",
    "StochasticReversion",
    "VolumeWeightedReversion",
    "create_mean_reversion_alphas",
    # ML alphas
    "MLAlpha",
    "XGBoostAlpha",
    "LightGBMAlpha",
    "RandomForestAlpha",
    "LinearAlpha",
    "NeuralNetAlpha",
    "EnsembleMLAlpha",
    "FeatureImportanceAlpha",
    "create_ml_alphas",
    # Alpha combiner
    "AlphaCombiner",
    "AlphaWeighter",
    "EqualWeighter",
    "ICWeighter",
    "SharpeWeighter",
    "InverseVolatilityWeighter",
    "OptimizedWeighter",
    "RankWeighter",
    "DecayWeighter",
    "AlphaOrthogonalizer",
    "AlphaNeutralizer",
    "WeightingMethod",
    "NeutralizationMethod",
    "OrthogonalizationMethod",
    "AlphaWeight",
    "CombinerConfig",
    "CompositeAlphaFactor",
    "create_combiner",
]
